#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Nov 13, 2021 05:04:54 PM CST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x458+2674+364
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::entry $top.tEn45 \
        \
        -font {-family {Microsoft JhengHei UI} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {} -background {} -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$top.tEn45" "TEntry1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command onBtnModifyClick_1 \
        -disabledforeground #a3a3a3 \
        -font {-family {Microsoft JhengHei UI} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Load 
    vTcl:DefineAlias "$top.but46" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Microsoft JhengHei UI} -size 15 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Image Index (Begin from 0)} 
    vTcl:DefineAlias "$top.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command onBtnModifyClick_2 \
        -disabledforeground #a3a3a3 \
        -font {-family {Microsoft JhengHei UI} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Transform 
    vTcl:DefineAlias "$top.but50" "Button2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Microsoft JhengHei UI} -size 15 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Target Position} 
    vTcl:DefineAlias "$top.lab51" "Label2" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $top.tEn53 \
        \
        -font {-family {Microsoft JhengHei UI} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {} -background {} -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$top.tEn53" "TEntry2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command onBtnModifyClick_3 \
        -disabledforeground #a3a3a3 \
        -font {-family {Microsoft JhengHei UI} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Save 
    vTcl:DefineAlias "$top.but54" "Button3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Microsoft JhengHei UI} -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {(left corner of the eye -> reft corner of the eye -> nose)} 
    vTcl:DefineAlias "$top.lab45" "Label1_2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Microsoft JhengHei UI} -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {After loading the image, please click the selected postion of it.} 
    vTcl:DefineAlias "$top.lab47" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Microsoft JhengHei UI} -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {default is (65, 90)_(95, 90)_(80, 120)_(160, 190)} 
    vTcl:DefineAlias "$top.lab49" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Microsoft JhengHei UI} -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {(x1, y1)_(x2, y2)_(x3, y3)_(H, W), where x & y are in the same order as above.} 
    vTcl:DefineAlias "$top.lab46" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tEn45 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.218 -width 0 -relwidth 0.9 \
        -height 0 -relheight 0.065 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.328 -width 68 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.022 -width 0 -relwidth 0.542 \
        -height 0 -relheight 0.092 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.786 -width 100 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.48 -width 0 -relwidth 0.342 \
        -height 0 -relheight 0.092 -anchor nw -bordermode ignore 
    place $top.tEn53 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.677 -width 0 -relwidth 0.9 \
        -height 0 -relheight 0.063 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 0 -relx 0.433 -y 0 -rely 0.786 -width 68 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.153 -width 0 -relwidth 0.783 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.109 -width 0 -relwidth 0.783 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.611 -width 0 -relwidth 0.783 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.568 -width 0 -relwidth 0.917 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

